{"name": "test_2_1", "status": "failed", "statusDetails": {"message": "AssertionError: assert 2 == 3", "trace": "self = <Chapter_11.Storm_11_1.test_2_storm.TestDemo object at 0x04405B10>\n\n    @allure.story(\"测试用例2-1\")\n    @allure.severity(\"minor\")\n    def test_2_1(self):\n        \"\"\"\n        用例描述：这是第一条用例的描述\n        \"\"\"\n        #allure.MASTER_HELPER.description(\"11111111111111\")\n        a = 1 + 1\n>       assert a == 3  # 断言失败\nE       assert 2 == 3\n\ntest_2_storm.py:13: AssertionError"}, "description": "\n        用例描述：这是第一条用例的描述\n        ", "start": 1589641498135, "stop": 1589641498135, "uuid": "0ac6f40e-c585-4e25-b60a-dd97be0c6526", "historyId": "e70aed44d8d77635bdcf33bb9888f5a5", "testCaseId": "9986768de4158fab4fe79ce64269b4d8", "fullName": "test_2_storm.TestDemo#test_2_1", "labels": [{"name": "feature", "value": "测试场景2"}, {"name": "severity", "value": "minor"}, {"name": "story", "value": "测试用例2-1"}, {"name": "suite", "value": "test_2_storm"}, {"name": "subSuite", "value": "TestDemo"}, {"name": "host", "value": "DESKTOP-2VF9P2M"}, {"name": "thread", "value": "6624-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_2_storm"}]}